<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Open Browser</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>c484eaa4-2474-41bd-9e2e-e603737f60e7</testSuiteGuid>
   <testCaseLink>
      <guid>33339c3e-ce4f-434d-851a-9b4c94fa8852</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/00 Common/Open Browser with set Address (URL)</testCaseId>
      <testDataLink>
         <combinationType>MANY</combinationType>
         <id>5d09cdc8-fc77-4d15-9ab1-2ad5a8bedeee</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value>1-5</value>
         </iterationEntity>
         <testDataId>Data Files/SampleDataInquiry</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56932eeb-2a9c-46ff-aa81-c46b23b7b6e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4bb67b35-5fff-47f5-b87a-1b1d3db5e17d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5d09cdc8-fc77-4d15-9ab1-2ad5a8bedeee</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Company</value>
         <variableId>e707ff48-3597-4d30-83b8-60fed5500654</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5d09cdc8-fc77-4d15-9ab1-2ad5a8bedeee</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>productType</value>
         <variableId>554d11e6-8db2-43a2-86be-2f2f4e03f848</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5d09cdc8-fc77-4d15-9ab1-2ad5a8bedeee</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>KTP</value>
         <variableId>40b228bb-7244-43de-b297-89752a2c96b4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5d09cdc8-fc77-4d15-9ab1-2ad5a8bedeee</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Name</value>
         <variableId>75821d0e-efdf-429f-803a-1825d0b9be8e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5d09cdc8-fc77-4d15-9ab1-2ad5a8bedeee</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>DOB</value>
         <variableId>5b01de2b-2d3e-4f04-8669-f2d044cd813f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
